name = "frontend-test"
type = "webpack"
account_id = "6045b0c922c5f02ca8efe49010a2e687"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "modules"
main = "./.next/server/index.js"
